cities:

# North
- name: New_Delhi
  latitude: 28.6139
  longitude: 77.2090

- name: Chandigarh
  latitude: 30.7333
  longitude: 76.7794

- name: Shimla
  latitude: 31.1048
  longitude: 77.1734

- name: Dehradun
  latitude: 30.3165
  longitude: 78.0322

- name: Srinagar
  latitude: 34.0837
  longitude: 74.7973

- name: Amritsar
  latitude: 31.6340
  longitude: 74.8723

- name: Jammu
  latitude: 32.7266
  longitude: 74.8570

- name: Ludhiana
  latitude: 30.9000
  longitude: 75.8573

- name: Agra
  latitude: 27.1767
  longitude: 78.0081

- name: Meerut
  latitude: 28.9845
  longitude: 77.7064

# West

- name: Mumbai
  latitude: 19.0760
  longitude: 72.8777

- name: Pune
  latitude: 18.5204
  longitude: 73.8567

- name: Ahmedabad
  latitude: 23.0225
  longitude: 72.5714

- name: Jaipur
  latitude: 26.9124
  longitude: 75.7873

- name: Jodhpur
  latitude: 26.2389
  longitude: 73.0243

- name: Surat
  latitude: 21.1702
  longitude: 72.8311

- name: Vadodara
  latitude: 22.3072
  longitude: 73.1812

- name: Rajkot
  latitude: 22.3039
  longitude: 70.8022

- name: Nashik
  latitude: 19.9975
  longitude: 73.7898

- name: Udaipur
  latitude: 24.5854
  longitude: 73.7125

# South

- name: Chennai
  latitude: 13.0827
  longitude: 80.2707

- name: Bengaluru
  latitude: 12.9716
  longitude: 77.5946

- name: Hyderabad
  latitude: 17.3850
  longitude: 78.4867

- name: Kochi
  latitude: 9.9312
  longitude: 76.2673

- name: Mysuru
  latitude: 12.2958
  longitude: 76.6394

- name: Coimbatore
  latitude: 11.0168
  longitude: 76.9558

- name: Madurai
  latitude: 9.9252
  longitude: 78.1198

- name: Visakhapatnam
  latitude: 17.6868
  longitude: 83.2185

- name: Mangalore
  latitude: 12.9141
  longitude: 74.8560

- name: Thiruvananthapuram
  latitude: 8.5241
  longitude: 76.9366

# East

- name: Kolkata
  latitude: 22.5726
  longitude: 88.3639

- name: Bhubaneswar
  latitude: 20.2961
  longitude: 85.8245

- name: Patna
  latitude: 25.5941
  longitude: 85.1376

- name: Ranchi
  latitude: 23.3441
  longitude: 85.3096

- name: Cuttack
  latitude: 20.4625
  longitude: 85.8830

- name: Durgapur
  latitude: 23.5204
  longitude: 87.3119

- name: Asansol
  latitude: 23.6739
  longitude: 86.9524

- name: Siliguri
  latitude: 26.7271
  longitude: 88.3953

- name: Gaya
  latitude: 24.7914
  longitude: 85.0002

- name: Muzaffarpur
  latitude: 26.1209
  longitude: 85.3647

# Central + North-East

- name: Bhopal
  latitude: 23.2599
  longitude: 77.4126

- name: Nagpur
  latitude: 21.1458
  longitude: 79.0882

- name: Raipur
  latitude: 21.2514
  longitude: 81.6296

- name: Indore
  latitude: 22.7196
  longitude: 75.8577

- name: Jabalpur
  latitude: 23.1815
  longitude: 79.9864

- name: Guwahati
  latitude: 26.1445
  longitude: 91.7362

- name: Shillong
  latitude: 25.5788
  longitude: 91.8933

- name: Agartala
  latitude: 23.8315
  longitude: 91.2868

- name: Imphal
  latitude: 24.8170
  longitude: 93.9368

- name: Aizawl
  latitude: 23.7271
  longitude: 92.7176